#:schema node_modules/wrangler/config-schema.json
name = "my-resume"
main = "src/backend.ts"
compatibility_date = "2024-10-18"
assets = { directory = "./client/dist/", binding = "ASSETS" }

[[vectorize]]
binding = "VECTORIZE"
index_name = "resume-index"

[ai]
binding = "AI"
# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
